### ISSUE TITLE
Results show duplicate questions/variables from Next steps

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#13]
Selected all CLS COVID waves 1 and waves 2 for match text, match text, equivalent questions. It is showing Next Steps questions/variables twice. 

[Display_CLS.txt](https://github.com/CLOSER-Cohorts/Equivalences/files/6148840/Display_CLS.txt)

![image](https://user-images.githubusercontent.com/16664703/111307654-a8f47c80-8651-11eb-92d0-b0c325092114.png)

It is displaying deprecated items.

**Comment by BlinkyBill62** [comment]
I have checked just the Next Steps Covid studies and if you go from the Display page to Variable page although the details are the same they have different variable item urn's. Please see screen shot below.
![Next Steps](https://user-images.githubusercontent.com/51624515/111653345-bfd8d180-87ff-11eb-8f1f-88d923b9c342.png)

**Comment by HayleyMills** [comment]
Thanks @BlinkyBill62 but one is deprecated (the uk.cls.bcs version). Can we ignore deprecated items please?

**Comment by BlinkyBill62** [comment]
I will investigate now.

**Comment by BlinkyBill62** [comment]
I looked at skipping deprecated items. the item you mention is marked as deprecated = false. I know I deprecated the dataset that contains this variable. I checked as did Jon and all were deprecated but now none of the items in the dataset are deprecated.

**Comment by HayleyMills** [comment]
@BlinkyBill62 so is this an issue with the tool or with the deprecation in the portal?

**Comment by BlinkyBill62** [comment]
I can only speculate on the reason. On the 22/02/2021 I deprecated the dataset that contains this variable. My first thought would have been would be there had been a restore after that date which would have overwritten the deprecation. On further investigation the latest version for variables in the dataset I deprecated is 23/02/2021. This is version 2 but SDK seems to indicate there is no version 1. My understanding of the repository is this should not be the case as nothing should ever be deleted in the repository. I would suggest you discuss this with Jon as it is possible the repository database is the issue.

The equivalences tool only retrieves information so it is not the issue. If the issue was with the issue there should be evidence in the versions.

Hope this makes sense. Happy to discuss.

**Comment by spuddybike** [comment]
We just need to make sure the tool ignores deprecated items ... we can fix the data if there is an issue 
Ta
Jon

**Comment by BlinkyBill62** [comment]
The tool has been updated to ignore deprecated variables. Currently there are no deprecated variables in the repository on staging so it is not possible to test that deprecated items will be ignored.

**Comment by HayleyMills** [comment]
Thanks we can retest this when that is the case.

**Comment by HayleyMills** [comment]
Tested on https://clsr-ppcolw01n.addev.ucl.ac.uk:19000/ and it is workign correctly - only showing one set of Next steps.
