### ISSUE TITLE
Upload csv for page 2 not working for all files?

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/Equivalences#20]
Should it be possible to upload the csv from the second page through the select view? I have tried to upload this file (as a csv version), but I receieve the error 
Error.
An error occurred while processing your request.

I tried to the trim the file, but that still didn't work.
[Equivelancies_alspac_EA_page2.txt](https://github.com/CLOSER-Cohorts/Equivalences/files/6533737/Equivelancies_alspac_EA_page2.txt)

Tried again, with this file, and it did load. 
[Equivelancies_sws_12_page2.txt](https://github.com/CLOSER-Cohorts/Equivalences/files/6533799/Equivelancies_sws_12_page2.txt)

**Comment by BlinkyBill62** [comment]
There is an issue where there are multiple concepts within an equivalence. The issue is when I retrieve Variable Group for a Variable. It is not on all studies. Currently I have identified an issue on Alspac EA but it is possible it will be on other studies. I have put a work around so the error will not occur and the equivalences tool will load all csv's. This has not addressed the issue and it will need further investigation.

**Comment by HayleyMills** [comment]
The csv for Output Equivalenices can be downloaded and uploaded on the select page without problems.
